### ISSUE TITLE
PlatformLinuxClang gets passed invalid compiler flags

### ISSUE THREAD

**Issue by mrzzzrm** [cginternals/gloperate#112]
Haven't checked all the others, but at least ```-Wno-pragmas``` is not a flag on clang 3.4.
Have you considered establishing a central repository for the cmake/Platform*.cmake files? Fixing them in an increasing number of projects seems error prone (e.g. libzeug configures clang wih a completely different set of compiler warning flags)

**Comment by cgcostume** [comment]
@mrzzzrm check out https://github.com/cginternals/cmake-init :smile:

**Comment by mrzzzrm** [comment]
cmake-init doesn't even include a PlatformLinuxClang.config as far as I can tell? And if it would it doesn't change that 
* gloperate doesn't build for clang 3.4 atm
* all your projects have local copies of the Platform*.cmake files that need manual fixing (and as I get the impression from libzeug and gloperate, have already diverged).

**Comment by scheibel** [comment]
https://github.com/cginternals/cmake-init/pull/13 there it is ;)

And the manual copy and individual maintenance is because of the different compiler flags we have to provide for the different dependencies we use in each project. In a good world, this wouldn't be necessary but currently we have to disable some warnings to keep sane.

**Comment by scheibel** [comment]
I think this issue is obsolete with the introduction of cmake-init 2.0 in december?
