### ISSUE TITLE
Add TextureLoaderStage

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#202]
Implement a stage with the following interface.

Input:
- file path: the file to load the texture from (cppassist::FilePath)

Output:
- texture: texture object (gloperate::Texture, to be defined)

Behavior:
Load a texture from the specified file path. Use the gloperate::Loader interface. Infer the texture creation parameters from the file name and file contents.

**Comment by scheibel** [comment]
It seems like there is already a ```TextureLoadStage``` since a couple of months. Is this ticket finished or what are the expected differences to the current implementation?

**Comment by sbusch42** [comment]
The stage could be extended to support dynamic inputs, so that one can load many textures with a single stage. Apart from that I would say the stage is fine. Missing features do not belong to the stage itself, but to missing loaders (e.g., a .raw and .glraw texture loader should finally be implemented).
