### ISSUE TITLE
PropertyGroup interface

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#58]
Although a ```Painter``` may be an object in terms of reflection and scriptability, it is kind of strange I can call methods like this on a ```Painter```:

```cpp
Painter::toVariant
Painter::fromVariant
Painter::count
Painter::value
Painter::group
Painter::isEmpty
Painter::indexOf
Painter::clear
Painter::forEach*
```

These are all methods from ```PropertyGroup```. The results / behavior of some methods are extremely hard to understand. For example, I'm confused that ```clear``` only clears all properties and no registered functions. Beside that, may a ```clear``` method on a Painter could mean something completely different?
The interface from ```Object``` is just fine.

**Comment by sbusch42** [comment]
This is the exact reason why I'm in favor of precise method names, e.g. clearProperties() instead of clear(). This has been refused with the remark that it would be a "duplication", a class PropertyGroup should have the name clear() and not clearProperties. Unfortunately, this approach does not hold when using inheritance, and something like clear() is especially critical since it is used a lot in different circumstances.

**Comment by scheibel** [comment]
This is a crucial point in designing object oriented classes and interfaces.
I think the (overall, not our specific) goal is to provide an interface to a class, that is minimal (i.e., no redundancy) and understandable. For a class that should be used directly, this means that the class name should not be included in any method name. For a class that should by used by subclassing, this may mean that the class name is relevant in the method names.

Normally, I would prefer composition over inheritance so that both solutions can be provided.
First, the actual class with no class name mentioned in its method names and second, a using class with a delegating interface that adds the class name to the method names.

What we currently have is the subclassing case with no class names in method names (only for ```PropertyGroup```, the ```Object``` interface is designed for this use case).

I think a solution may be to design the interface for a painter disregarding the current interfaces of ```Object``` and ```PropertyGroup``` and ater that, we decide what to do with the superclass interfaces.

**Comment by cgcostume** [comment]
I would prefer function names within the context of their class (since this is default for most libraries) and favor composition over inheritance in this case. Since there is probably no further rational here, we could wait/trigger on some more feedback relating this design decision.

**Comment by sbusch42** [comment]
This is like saying QObject ought to be used by composition rather than by inheritance, which I find extremely strange. It's much easier to think of reflection as extending an already existing class to expose a reflection interface (by deriving the class from Object), then suddenly it's all much easier to use, because you don't have to manage property groups by yourself and keep track of deleting them, you can reuse existing hierarchies instead of replecating a new one in form of property groups outside the class etc. And I do not say it should be prohibited to use properties that way, I see use cases where it whould make perfectly sense to create and manage property groups dynamically, it just shouldn't be the default. So please don't make the property interface more complicated than it has to be and let's indeed encourage a simple use, not the complicated one that unfortunately has been used so far by most projects.

**Comment by sbusch42** [comment]
And for the function names: as often, a middle ground would help here instead of always jumping to the extreme. I completely agree that, e.g. a plugin should have a method getName(), and not getPluginName(), but when managing sub-objects, I rather have the name of what is managed here, e.g. addPlugin() instead of add(). If I have a plugin manager, it's not obvious what add() means, it can be a plugin, or a search path, so I really miss the information there. And with such a default way of naming functions it would also make the problem go away that I have to decide in advance if this class is "intended for inheritance" or "intended for composition" - in fact we should not make that decision at all, but let the user choose what to do and leave as much choice as possible. Which we already had established as a good practice anyway.

**Comment by j-o** [comment]
I think, from a conceptual point of view, it is kind of strange to say an `Object` *is* a `PropertyGroup` (and therefore also a `Property`). It is more intuitive to say an `Object` *has* `Property`s (and `Function`s), so I would say this is a case for composition and a problem of libzeug, not gloperate. `Object` could then provide delegating methods for properties and functions.
