### ISSUE TITLE
System capability

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#65]
I want to propose a capability that enables a painter and a viewer to negotiate the features available.
The two use cases are:
(1) The painter wants to tell the viewer its minimum requirements; without them the painter isn't able to be initialized and executed.
(2) The viewer tells the painter the maximum available system components and the painter can adapt to them.

The targeted system components and requirements include mainly the available OpenGL version and OpenGL extensions. Further, the number of CPU cores, the availability of CUDA, Vulkan, OpenVX, or OpenCL is imaginable.

Your opinions?

**Comment by sbusch42** [comment]
(1) I think an application should rather run slowly or with errors, instead of refusing to start at all because of some metric (memory size, ...). Let the user decide if the result is good enough.
(2) that could be implemented completely inside the painter, by using some utility functions, I don't see a need for a direct interface from the viewer to the painter here.

Do we need to discuss this further for gloperate 2.0? Otherwise please close ...
